version: 2.1

jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            docker build -t dbt:latest .
      - deploy:
          name: Deploy docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker tag dbt:$CIRCLE_TAG $DOCKER_USER/dbt:$CIRCLE_TAG
            docker tag dbt:latest $DOCKER_USER/dbt:latest
            docker push $DOCKER_USER/dbt:$CIRCLE_TAG
            docker push $DOCKER_USER/dbt:latest

workflows:
  build:
    jobs:
      - build:
          context:
            - docker